import { THEME_COLORS } from '@/types/colors.types'

export const PREMIUM_THEME_COLORS: readonly THEME_COLORS[] = [
	THEME_COLORS.PREMIUM,
	THEME_COLORS.PREMIUM_ORCHID,
	THEME_COLORS.PREMIUM_DENIM,
	THEME_COLORS.PREMIUM_BLUSH,
	THEME_COLORS.PREMIUM_CLAY,
	THEME_COLORS.PREMIUM_GRAPHITE,
	THEME_COLORS.PREMIUM_HONEY,
	THEME_COLORS.PREMIUM_IRIS,
	THEME_COLORS.PREMIUM_CITRINE,
	THEME_COLORS.PREMIUM_LAGOON,
	THEME_COLORS.PREMIUM_LILAC,
	THEME_COLORS.PREMIUM_SPRING,
	THEME_COLORS.CUSTOM,
]

export function isPremiumOnlyTheme(theme: THEME_COLORS): boolean {
	return PREMIUM_THEME_COLORS.includes(theme)
}
