import ClientProviders from '@/components/providers/ClientProviders'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { Toaster } from 'sonner'
import './globals.css'

const montserratSans = Montserrat({
	variable: '--font-montserrat-sans',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const isDarkMode = true
	return (
		<html lang='en' className={isDarkMode ? 'dark' : ''}>
			<body className={`${montserratSans.variable}  antialiased`}>
				<ClientProviders>{children}</ClientProviders>
				<Toaster
					className='w-full max-w-[320px] max-[350px]:max-w-[280px]'
					position='top-right'
					toastOptions={{
						duration: 3000,
						style: {
							maxWidth: '320px',
							width: '100%',
						},
					}}
				/>
			</body>
		</html>
	)
}
