import { Montserrat } from 'next/font/google'
import { cookies } from 'next/headers'
import { Toaster } from 'sonner'

import ClientProviders from '@/components/providers/ClientProviders'
import { NextIntlClientProvider } from 'next-intl'
import type { Metadata } from 'next'
import './globals.css'

const montserratSans = Montserrat({
	variable: '--font-montserrat-sans',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: {
		icon: '/favicon.svg',
	},
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const isDarkMode = true
	const cookiesList = await cookies()
	const theme = cookiesList.get('theme')?.value || 'BLUE'
	const locale = (cookiesList.get('locale')?.value || 'uk') as 'uk' | 'en'

	const messages = (await import(`@/locales/${locale}.json`)).default
	return (
		<html
			lang='en'
			className={`theme-${theme.toLowerCase()} ${isDarkMode ? 'dark' : ''}`}
		>
			<body className={`${montserratSans.variable}  antialiased`}>
				<NextIntlClientProvider locale={locale} messages={messages}>
					<ClientProviders>{children}</ClientProviders>
				</NextIntlClientProvider>
				<Toaster
					className='w-full max-w-[320px] max-[350px]:max-w-[280px] !z-60 !important '
					position='top-right'
					toastOptions={{
						duration: 3000,
						style: {
							maxWidth: '320px',
							width: '100%',
							pointerEvents: 'auto',
						},
					}}
				/>
			</body>
		</html>
	)
}
