import { Toaster } from '@/components/ui/sonner'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'

const montserratSans = Montserrat({
	variable: '--font-montserrat-sans',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${montserratSans.variable}  antialiased`}>
				{children}

				<Toaster
					position='top-right'
					toastOptions={{
						duration: 3000,
						style: {
							maxWidth: '320px',
							width: '100%',
						},
					}}
				/>
			</body>
		</html>
	)
}
